name: Vixio
description: Vixio, The Discord addon created to meet all of your Discord needs.
main: me.iblitzkriegi.vixio.Vixio
version: 2.0.9-patched
author: iBlitzkriegi, sky_high (Pikachu), Olyno, carlodrift
website: https://github.com/carlodrift/vixio
depend: [Skript]
commands:
  vixio:
    description: Default command for Vixio
    usage: /<command>
